/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppLogisticsShipmentsRouteImport } from './routes/app.logistics-shipments'
import { Route as AppLogisticsInventoryRouteImport } from './routes/app.logistics-inventory'
import { Route as AppLogisticsRouteImport } from './routes/app.logistics'
import { Route as AppHrRecruitmentRouteImport } from './routes/app.hr-recruitment'
import { Route as AppHrPayrollRouteImport } from './routes/app.hr-payroll'
import { Route as AppHrRouteImport } from './routes/app.hr'
import { Route as AppFinanceReportsRouteImport } from './routes/app.finance-reports'
import { Route as AppFinanceInvoicesRouteImport } from './routes/app.finance-invoices'
import { Route as AppFinanceBudgetsRouteImport } from './routes/app.finance-budgets'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppEquityRouteImport } from './routes/app.equity'
import { Route as AppCeoRouteImport } from './routes/app.ceo'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppLogisticsShipmentsRoute = AppLogisticsShipmentsRouteImport.update({
  id: '/logistics-shipments',
  path: '/logistics-shipments',
  getParentRoute: () => AppRoute,
} as any)
const AppLogisticsInventoryRoute = AppLogisticsInventoryRouteImport.update({
  id: '/logistics-inventory',
  path: '/logistics-inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppLogisticsRoute = AppLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRecruitmentRoute = AppHrRecruitmentRouteImport.update({
  id: '/hr-recruitment',
  path: '/hr-recruitment',
  getParentRoute: () => AppRoute,
} as any)
const AppHrPayrollRoute = AppHrPayrollRouteImport.update({
  id: '/hr-payroll',
  path: '/hr-payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceReportsRoute = AppFinanceReportsRouteImport.update({
  id: '/finance-reports',
  path: '/finance-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceInvoicesRoute = AppFinanceInvoicesRouteImport.update({
  id: '/finance-invoices',
  path: '/finance-invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceBudgetsRoute = AppFinanceBudgetsRouteImport.update({
  id: '/finance-budgets',
  path: '/finance-budgets',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppEquityRoute = AppEquityRouteImport.update({
  id: '/equity',
  path: '/equity',
  getParentRoute: () => AppRoute,
} as any)
const AppCeoRoute = AppCeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/ceo': typeof AppCeoRoute
  '/app/equity': typeof AppEquityRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/finance-budgets': typeof AppFinanceBudgetsRoute
  '/app/finance-invoices': typeof AppFinanceInvoicesRoute
  '/app/finance-reports': typeof AppFinanceReportsRoute
  '/app/hr': typeof AppHrRoute
  '/app/hr-payroll': typeof AppHrPayrollRoute
  '/app/hr-recruitment': typeof AppHrRecruitmentRoute
  '/app/logistics': typeof AppLogisticsRoute
  '/app/logistics-inventory': typeof AppLogisticsInventoryRoute
  '/app/logistics-shipments': typeof AppLogisticsShipmentsRoute
  '/app/messages': typeof AppMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/ceo': typeof AppCeoRoute
  '/app/equity': typeof AppEquityRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/finance-budgets': typeof AppFinanceBudgetsRoute
  '/app/finance-invoices': typeof AppFinanceInvoicesRoute
  '/app/finance-reports': typeof AppFinanceReportsRoute
  '/app/hr': typeof AppHrRoute
  '/app/hr-payroll': typeof AppHrPayrollRoute
  '/app/hr-recruitment': typeof AppHrRecruitmentRoute
  '/app/logistics': typeof AppLogisticsRoute
  '/app/logistics-inventory': typeof AppLogisticsInventoryRoute
  '/app/logistics-shipments': typeof AppLogisticsShipmentsRoute
  '/app/messages': typeof AppMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/ceo': typeof AppCeoRoute
  '/app/equity': typeof AppEquityRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/finance-budgets': typeof AppFinanceBudgetsRoute
  '/app/finance-invoices': typeof AppFinanceInvoicesRoute
  '/app/finance-reports': typeof AppFinanceReportsRoute
  '/app/hr': typeof AppHrRoute
  '/app/hr-payroll': typeof AppHrPayrollRoute
  '/app/hr-recruitment': typeof AppHrRecruitmentRoute
  '/app/logistics': typeof AppLogisticsRoute
  '/app/logistics-inventory': typeof AppLogisticsInventoryRoute
  '/app/logistics-shipments': typeof AppLogisticsShipmentsRoute
  '/app/messages': typeof AppMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/sitemap.xml'
    | '/app/ceo'
    | '/app/equity'
    | '/app/finance'
    | '/app/finance-budgets'
    | '/app/finance-invoices'
    | '/app/finance-reports'
    | '/app/hr'
    | '/app/hr-payroll'
    | '/app/hr-recruitment'
    | '/app/logistics'
    | '/app/logistics-inventory'
    | '/app/logistics-shipments'
    | '/app/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/sitemap.xml'
    | '/app/ceo'
    | '/app/equity'
    | '/app/finance'
    | '/app/finance-budgets'
    | '/app/finance-invoices'
    | '/app/finance-reports'
    | '/app/hr'
    | '/app/hr-payroll'
    | '/app/hr-recruitment'
    | '/app/logistics'
    | '/app/logistics-inventory'
    | '/app/logistics-shipments'
    | '/app/messages'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/sitemap.xml'
    | '/app/ceo'
    | '/app/equity'
    | '/app/finance'
    | '/app/finance-budgets'
    | '/app/finance-invoices'
    | '/app/finance-reports'
    | '/app/hr'
    | '/app/hr-payroll'
    | '/app/hr-recruitment'
    | '/app/logistics'
    | '/app/logistics-inventory'
    | '/app/logistics-shipments'
    | '/app/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logistics-shipments': {
      id: '/app/logistics-shipments'
      path: '/logistics-shipments'
      fullPath: '/app/logistics-shipments'
      preLoaderRoute: typeof AppLogisticsShipmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logistics-inventory': {
      id: '/app/logistics-inventory'
      path: '/logistics-inventory'
      fullPath: '/app/logistics-inventory'
      preLoaderRoute: typeof AppLogisticsInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logistics': {
      id: '/app/logistics'
      path: '/logistics'
      fullPath: '/app/logistics'
      preLoaderRoute: typeof AppLogisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hr-recruitment': {
      id: '/app/hr-recruitment'
      path: '/hr-recruitment'
      fullPath: '/app/hr-recruitment'
      preLoaderRoute: typeof AppHrRecruitmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hr-payroll': {
      id: '/app/hr-payroll'
      path: '/hr-payroll'
      fullPath: '/app/hr-payroll'
      preLoaderRoute: typeof AppHrPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hr': {
      id: '/app/hr'
      path: '/hr'
      fullPath: '/app/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance-reports': {
      id: '/app/finance-reports'
      path: '/finance-reports'
      fullPath: '/app/finance-reports'
      preLoaderRoute: typeof AppFinanceReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance-invoices': {
      id: '/app/finance-invoices'
      path: '/finance-invoices'
      fullPath: '/app/finance-invoices'
      preLoaderRoute: typeof AppFinanceInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance-budgets': {
      id: '/app/finance-budgets'
      path: '/finance-budgets'
      fullPath: '/app/finance-budgets'
      preLoaderRoute: typeof AppFinanceBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equity': {
      id: '/app/equity'
      path: '/equity'
      fullPath: '/app/equity'
      preLoaderRoute: typeof AppEquityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ceo': {
      id: '/app/ceo'
      path: '/ceo'
      fullPath: '/app/ceo'
      preLoaderRoute: typeof AppCeoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCeoRoute: typeof AppCeoRoute
  AppEquityRoute: typeof AppEquityRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppFinanceBudgetsRoute: typeof AppFinanceBudgetsRoute
  AppFinanceInvoicesRoute: typeof AppFinanceInvoicesRoute
  AppFinanceReportsRoute: typeof AppFinanceReportsRoute
  AppHrRoute: typeof AppHrRoute
  AppHrPayrollRoute: typeof AppHrPayrollRoute
  AppHrRecruitmentRoute: typeof AppHrRecruitmentRoute
  AppLogisticsRoute: typeof AppLogisticsRoute
  AppLogisticsInventoryRoute: typeof AppLogisticsInventoryRoute
  AppLogisticsShipmentsRoute: typeof AppLogisticsShipmentsRoute
  AppMessagesRoute: typeof AppMessagesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCeoRoute: AppCeoRoute,
  AppEquityRoute: AppEquityRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppFinanceBudgetsRoute: AppFinanceBudgetsRoute,
  AppFinanceInvoicesRoute: AppFinanceInvoicesRoute,
  AppFinanceReportsRoute: AppFinanceReportsRoute,
  AppHrRoute: AppHrRoute,
  AppHrPayrollRoute: AppHrPayrollRoute,
  AppHrRecruitmentRoute: AppHrRecruitmentRoute,
  AppLogisticsRoute: AppLogisticsRoute,
  AppLogisticsInventoryRoute: AppLogisticsInventoryRoute,
  AppLogisticsShipmentsRoute: AppLogisticsShipmentsRoute,
  AppMessagesRoute: AppMessagesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
